import os
import sqlite3
from pathlib import Path
from contextlib import contextmanager

from dotenv import load_dotenv

load_dotenv()


BACKEND_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BACKEND_DIR / "data"
DATABASE_FILE = DATA_DIR / "career_copilot.db"

DATABASE_URL = os.getenv("DATABASE_URL")


# ============================================================
# POSTGRESQL COMPATIBILITY CURSOR
# ============================================================

class PostgreSQLCursor:
    """
    Compatibility wrapper so existing services can continue using:
      - SQLite-style ? placeholders
      - cursor.lastrowid
    """

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        query = query.replace("?", "%s")

        if params is None:
            return self._cursor.execute(query)

        return self._cursor.execute(query, params)

    def executemany(self, query, params):
        query = query.replace("?", "%s")
        return self._cursor.executemany(query, params)

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def lastrowid(self):
        # PostgreSQL LASTVAL() returns the last sequence value
        # generated in this database session.
        self._cursor.execute(
            "SELECT LASTVAL() AS id"
        )

        row = self._cursor.fetchone()

        if row is None:
            return None

        if isinstance(row, dict):
            return row["id"]

        return row[0]

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgreSQLConnection:
    """
    Compatibility wrapper around psycopg2 connection.
    """

    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        from psycopg2.extras import DictCursor

        cursor = self._connection.cursor(
            cursor_factory=DictCursor
        )

        return PostgreSQLCursor(cursor)

    def commit(self):
        return self._connection.commit()

    def rollback(self):
        return self._connection.rollback()

    def close(self):
        return self._connection.close()

    def __enter__(self):
        self._connection.__enter__()
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        return self._connection.__exit__(
            exc_type,
            exc_value,
            traceback
        )

    def __getattr__(self, name):
        return getattr(self._connection, name)


# ============================================================
# SQLITE
# ============================================================

def ensure_data_directory():
    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )


def get_sqlite_connection():
    ensure_data_directory()

    connection = sqlite3.connect(
        DATABASE_FILE
    )

    connection.row_factory = sqlite3.Row

    return connection


# ============================================================
# POSTGRESQL
# ============================================================

def get_postgres_connection():
    import psycopg2

    connection = psycopg2.connect(
        DATABASE_URL
    )

    return PostgreSQLConnection(
        connection
    )


# ============================================================
# DATABASE CONNECTION
# ============================================================

@contextmanager
def get_connection():

    # Production:
    # DATABASE_URL -> PostgreSQL / Supabase
    if DATABASE_URL:

        connection = get_postgres_connection()

        try:
            yield connection
            connection.commit()

        except Exception:
            connection.rollback()
            raise

        finally:
            connection.close()

        return

    # Local development:
    # fallback to SQLite
    connection = get_sqlite_connection()

    try:
        yield connection
        connection.commit()

    except Exception:
        connection.rollback()
        raise

    finally:
        connection.close()


# ============================================================
# POSTGRESQL INITIALIZATION
# ============================================================

def initialize_postgresql_database():

    with get_connection() as connection:

        cursor = connection.cursor()

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS jobs (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source TEXT NOT NULL,
                source_job_id TEXT,
                title TEXT NOT NULL,
                company TEXT,
                location TEXT,
                description TEXT,
                url TEXT,
                salary_min DOUBLE PRECISION,
                salary_max DOUBLE PRECISION,
                created_at TEXT,
                deadline TEXT,
                remote_status TEXT DEFAULT 'UNKNOWN',
                remote_confidence TEXT DEFAULT 'UNKNOWN',
                first_seen_at TEXT NOT NULL,
                last_seen_at TEXT NOT NULL,
                UNIQUE(source, source_job_id)
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_evaluations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT NOT NULL,
                provider TEXT NOT NULL,
                model TEXT,
                profile_version TEXT DEFAULT 'v1',
                match_score DOUBLE PRECISION,
                fit_summary TEXT,
                key_pros TEXT,
                key_gaps TEXT,
                recommended_action TEXT,
                draft_outreach TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id)
                    ON DELETE CASCADE
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS opportunity_assessments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT NOT NULL UNIQUE,
                geo_status TEXT NOT NULL,
                geo_confidence TEXT DEFAULT 'LOW',
                geo_reason TEXT,
                opportunity_score DOUBLE PRECISION,
                priority TEXT,
                final_action TEXT DEFAULT 'REVIEW',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id)
                    ON DELETE CASCADE
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS applications (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id BIGINT NOT NULL,
                ai_evaluation_id BIGINT,
                application_channel TEXT,
                cv_version TEXT,
                status TEXT NOT NULL DEFAULT 'SAVED',
                applied_at TEXT,
                last_updated_at TEXT NOT NULL,
                notes TEXT,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id)
                    ON DELETE CASCADE,
                FOREIGN KEY(ai_evaluation_id)
                    REFERENCES ai_evaluations(id)
                    ON DELETE SET NULL
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS application_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                application_id BIGINT NOT NULL,
                event_type TEXT NOT NULL,
                event_date TEXT NOT NULL,
                notes TEXT,
                FOREIGN KEY(application_id)
                    REFERENCES applications(id)
                    ON DELETE CASCADE
            )
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_source
            ON jobs(source)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_company
            ON jobs(company)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_title
            ON jobs(title)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_applications_status
            ON applications(status)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_opportunity_priority
            ON opportunity_assessments(priority)
            """
        )


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

def initialize_database():

    if DATABASE_URL:
        initialize_postgresql_database()
        return

    # SQLite initialization for local development
    with get_connection() as connection:

        cursor = connection.cursor()

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS jobs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                source TEXT NOT NULL,
                source_job_id TEXT,
                title TEXT NOT NULL,
                company TEXT,
                location TEXT,
                description TEXT,
                url TEXT,
                salary_min REAL,
                salary_max REAL,
                created_at TEXT,
                deadline TEXT,
                remote_status TEXT DEFAULT 'UNKNOWN',
                remote_confidence TEXT DEFAULT 'UNKNOWN',
                first_seen_at TEXT NOT NULL,
                last_seen_at TEXT NOT NULL,
                UNIQUE(source, source_job_id)
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_evaluations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                job_id INTEGER NOT NULL,
                provider TEXT NOT NULL,
                model TEXT,
                profile_version TEXT DEFAULT 'v1',
                match_score REAL,
                fit_summary TEXT,
                key_pros TEXT,
                key_gaps TEXT,
                recommended_action TEXT,
                draft_outreach TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id)
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS opportunity_assessments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                job_id INTEGER NOT NULL UNIQUE,
                geo_status TEXT NOT NULL,
                geo_confidence TEXT DEFAULT 'LOW',
                geo_reason TEXT,
                opportunity_score REAL,
                priority TEXT,
                final_action TEXT DEFAULT 'REVIEW',
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id)
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS applications (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                job_id INTEGER NOT NULL,
                ai_evaluation_id INTEGER,
                application_channel TEXT,
                cv_version TEXT,
                status TEXT NOT NULL DEFAULT 'SAVED',
                applied_at TEXT,
                last_updated_at TEXT NOT NULL,
                notes TEXT,
                FOREIGN KEY(job_id)
                    REFERENCES jobs(id),
                FOREIGN KEY(ai_evaluation_id)
                    REFERENCES ai_evaluations(id)
            )
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS application_events (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                application_id INTEGER NOT NULL,
                event_type TEXT NOT NULL,
                event_date TEXT NOT NULL,
                notes TEXT,
                FOREIGN KEY(application_id)
                    REFERENCES applications(id)
            )
            """
        )

        # Safe migration: opportunity_assessments
        cursor.execute(
            "PRAGMA table_info(opportunity_assessments)"
        )

        columns = {
            row["name"]
            for row in cursor.fetchall()
        }

        if "geo_confidence" not in columns:
            cursor.execute(
                """
                ALTER TABLE opportunity_assessments
                ADD COLUMN geo_confidence TEXT
                DEFAULT 'LOW'
                """
            )

        if "final_action" not in columns:
            cursor.execute(
                """
                ALTER TABLE opportunity_assessments
                ADD COLUMN final_action TEXT
                DEFAULT 'REVIEW'
                """
            )

        # Safe migration: jobs
        cursor.execute(
            "PRAGMA table_info(jobs)"
        )

        job_columns = {
            row["name"]
            for row in cursor.fetchall()
        }

        if "deadline" not in job_columns:
            cursor.execute(
                """
                ALTER TABLE jobs
                ADD COLUMN deadline TEXT
                """
            )

        # Indexes
        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_source
            ON jobs(source)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_company
            ON jobs(company)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_jobs_title
            ON jobs(title)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_applications_status
            ON applications(status)
            """
        )

        cursor.execute(
            """
            CREATE INDEX IF NOT EXISTS
            idx_opportunity_priority
            ON opportunity_assessments(priority)
            """
        )


# ============================================================
# DIRECT EXECUTION
# ============================================================

if __name__ == "__main__":

    initialize_database()

    if DATABASE_URL:
        print(
            "PostgreSQL database initialized successfully."
        )
    else:
        print(
            "SQLite database initialized successfully."
        )
        print(
            f"Database file: {DATABASE_FILE}"
        )